### ISSUE TITLE
moderators can configure pool- and project-formation algorithms using a config file

### ISSUE THREAD

**Issue by heyheyjp** [LearnersGuild/echo#432]
Include a YAML file for configuring pool- and project-formation settings.

This is intended to be directly edited by moderators (mostly @shereefb, possibly @tannerwelsh) as part of an effort to find the right ingredients for creating pools and projects.

Example file format:

``` yaml
pools:
  - id: green
    elo_band: 0..1000
    advanced_players:
      - @bundacia
      - @shereefb
  - id: blue
    elo_band: 1001..2500
    advanced_players:
      - @jeffreywescott
      - @prattsj
project_limits:
  - elo_band: 0..1099
    max_projects: 1
  - elo_band: 1100..1299
    max_projects: 2
  - elo_band: 1300..1499
    max_projects: 3
  - elo_band: 1500..2000
    max_projects: 4
```

(see long discussion in https://github.com/LearnersGuild/game-cli/issues/82 for more context)
